### ISSUE TITLE
Cant turn off after it turns on

### ISSUE THREAD

**Issue by Coyote21** [AHilyard/EquipmentCompare#10]
I have tried different keybinds but all are the same. When I hold my cursor over an item (axe) and hold the bound key (P) it shows the compare tooltip, but then the tool tip wont ever go away, whether I'm holding the bound key or not.

It's like the "show/hide" option is toggled on and never toggled off.

Multiplayer Server: MC 1.18.2, Fabric-API 0.58.0, Iceberg 1.0.38

**Comment by AHilyard** [comment]
I can't reproduce this, perhaps it's a conflict with another mod or you have P bound to multiple actions?  Please post your latest.log file from when this most recently occurred.

**Comment by Coyote21** [comment]
Yes, was a conflict/issue with another mod. Unsure which one exactly but probably Just Enough Keys (JEK).

In my previous post I said I had the P key bound to equipcompare but I "simplified" the truth so I wouldn't have to explain about Just Enough Keys. In fact, it was bound the the Right Ctrl (RC) key, which is provided by JEK.

When asked to provide my latest.log I decided I should probably remap the bound key from RC to P just in case it mattered and found that if used with the P key it works fine, it's only the "extra" key combinations provided by Just Enough Keys that cause any issue.

Sorry if this wasted your time, but hopefully this might help someone in the future.

Love the mod by the way, truly one of those QoL mods that should be in Vanilla.
