### ISSUE TITLE
[1.16.5] Strange tooltip renderering when comparing

### ISSUE THREAD

**Issue by NielsPilgaard** [AHilyard/EquipmentCompare#12]
Whenever I shift+hover over a tool or weapon while I have one equipped, this happens:

![image](https://user-images.githubusercontent.com/21295394/197255305-b993b072-a73c-4d3c-8cdd-101bf2a44dde.png)

Original report: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/5241

**Comment by AHilyard** [comment]
Hmm, that _is_ strange.  I will look into this shortly, I suspect a conflicting mod.

**Comment by AHilyard** [comment]
Sorry for the delay, it has taken several days to narrow down the issue, but I've finally found that version 3.9+ of JustEnoughCalculation is causing this issue.  The source for this version hasn't been uploaded to their Github yet, but I will try to look into this to see if it is something I can fix from my side.

**Comment by AHilyard** [comment]
Looks like this bug is affecting a bunch of other mods, I believe this issue is related: https://github.com/Towdium/JustEnoughCalculation/issues/116

**Comment by NielsPilgaard** [comment]
Great work tracking it down!
