### ISSUE TITLE
Legacy Cloth Config API marked as dependancy on CurseForge

### ISSUE THREAD

**Issue by Mr1cecream** [AHilyard/EquipmentCompare#14]
Instead of the modern Cloth Config API, on CurseForge the legacy (1.17.1) one is marked as a required dependency, which breaks downloading dependencies automatically via the CurseForge API.

**Comment by AHilyard** [comment]
Thanks for pointing this out, I've removed it from the 1.19 version (as it's not actually used in that version).  I've also updated the older versions to use the non-deprecated Cloth Config API.
