### ISSUE TITLE
Mod crashing on load (Minecraft thinks its duplicated) 1.12.2

### ISSUE THREAD

**Issue by OfficialZygorg** [AHilyard/EquipmentCompare#16]
![image](https://user-images.githubusercontent.com/43007952/202853774-b5d80b2c-7630-4ce4-8144-7e61c550dee7.png)
![image](https://user-images.githubusercontent.com/43007952/202853796-5f5b880a-f0bc-4b48-94b7-1d6d7d3bc637.png)

As you can see, there's only one mod.
Created a new instance with the mod alone and it crashed.
Found the bug first on this modpack and tried to use it only alone in a clean instance.
https://www.curseforge.com/minecraft/modpacks/wynncraft-remastered

**Comment by AHilyard** [comment]
This is a known issue with GDLauncher on Minecraft versions 1.12.2 and earlier, affecting many mods.  In fact, I personally fixed the bug and submitted it as a PR a while back, as you can see here: https://github.com/gorilla-devs/GDLauncher/pull/1459#issuecomment-1266190737
This PR has not yet been merged unfortunately.  There may be other work arounds I'm unfamiliar with, but this is a GDLauncher problem.
