### ISSUE TITLE
[bug] comparison shows when I'm not wanting it too

### ISSUE THREAD

**Issue by Aces-and-Jacks** [AHilyard/EquipmentCompare#18]
Sometimes when I go into my inventory when I hover over an item it compares it when I'm not pressing shift. I have to press shift again to make it disappear. It doesn't happen all the time but it does happen pretty frequently

1.19.2

quilt

**Comment by Aces-and-Jacks** [comment]
Ok figured out how to reproduce this. 

Hold shift when hovering on a tool
press e to go out of inventory while holding shift

**Comment by AHilyard** [comment]
Thank you for bringing this to my attention, it's been fixed in the latest release. :)
