### ISSUE TITLE
Latest version isn't labeled 1.18.2

### ISSUE THREAD

**Issue by DWX12** [AHilyard/EquipmentCompare#3]
Latest version of Equipment Compare has a file name of 1.18.1 when it's labeled as 1.18.2 on curseforge.
EquipmentCompare-1.18.1-1.2.12.jar

Just a nitpicky thing that I saw as I was going through mods.

Thank you for taking the time to create this mod.

**Comment by AHilyard** [comment]
This file is labelled 1.18.1 because that is the earliest supported version for this file.  A new update will be uploaded soon that will be labelled 1.18.2 as that's the only version it supports however.
