### ISSUE TITLE
Crash when opening Wandering trader trade window

### ISSUE THREAD

**Issue by Simplebenja** [AHilyard/EquipmentCompare#33]
When you try to open the trade window the game crash
Forge: 1.20.1 47.1.28
Mod version: EquipmentCompare-1.20.1-forge-1.3.6
Iceberg version: Iceberg-1.20.1-forge-1.1.10
Windows 7 professional service pack 1 

[crash-2023-07-18_17.32.27-client.txt](https://github.com/AHilyard/EquipmentCompare/files/12089677/crash-2023-07-18_17.32.27-client.txt)

**Comment by SireOfTheQuags** [comment]
You're running windows 7... Like no offense but windows 7 is literally 12 years old now no wonder it's going to cause issues.

**Comment by Simplebenja** [comment]
> You're running windows 7... Like no offense but windows 7 is literally 12 years old now no wonder it's going to cause issues.

haha touche
