### ISSUE TITLE
[Fabric/1.18.2] Compare tooltip fails to display when comparing trinkets

### ISSUE THREAD

**Issue by MisterPeModder** [AHilyard/EquipmentCompare#4]
When hovering an item that can be equipped as a trinket, an  `InvokationTargetException` is thrown by the call to `TrinketSlot.canInsert()` in TrinketsHandler, causing the tooltip to not display.

This is caused by an incompatibility with newer Trinkets versions, updating the included Cardinal Components dependencies seems to resolve the issue.

#### Versions:
- Minecraft 1.18.2
- Fabric Loader: 0.13.3
- Fabric API: 1.0.38
- Equipment Compare: 1.2.11
- Trinkets: 3.3.0

**Comment by AHilyard** [comment]
Thanks for the report!  This has been fixed in the latest release on CurseForge. :)
