### ISSUE TITLE
 [1.21] Game does not start with ImmediatelyFast and Equipment Compare

### ISSUE THREAD

**Issue by OriginCode** [AHilyard/EquipmentCompare#40]
Log: https://mclo.gs/I4PlUMr

Tested with minimal reproducible environment: 4 mods: Fabric API, ImmediatelyFast, Iceberg (dependency of Equipment Compare) and Equipment Compare.

Disabling either ImmediatelyFast or Equipment Compare can solve the problem.

Ref: https://github.com/RaphiMC/ImmediatelyFast/issues/253

**Comment by XanderCrafter** [comment]
Can confirm.  Running over 120 mods, and immediately fast is the only compatibility issue.

**Comment by AHilyard** [comment]
This has been resolved in the latest update (please update both Equipment Compare and Iceberg).

**Comment by XanderCrafter** [comment]
Fix confirmed. Thank you!
