### ISSUE TITLE
Very minor suggestion to capitalize "Show comparison tooltip"

### ISSUE THREAD

**Issue by aghostofstarman255** [AHilyard/EquipmentCompare#7]
![2022-05-19](https://user-images.githubusercontent.com/79660102/169437001-603ebcec-c839-4d97-a945-33b9495bbc51.png)

Change "Show comparison tooltip" to "Show Comparison Tooltip" to be consistent with other controls.

**Comment by AHilyard** [comment]
Thanks for the suggestion.  You'll be happy to hear that in version 1.3.0, I've changed the keybind naming to a translatable string that defaults to "Show Comparison Tooltip".  😄
