### ISSUE TITLE
[1.19] Breaking changes in Forge require update please.

### ISSUE THREAD

**Issue by ProsperCraft** [AHilyard/EquipmentCompare#8]
https://gist.githubusercontent.com/ProsperCraft/517507b4fb3d8ba55363d2c087c9352e/raw/338441163bc3db3f9a5d79f228f95f747d4b4a99/gistfile1.txt

**Comment by AHilyard** [comment]
Thanks for letting me know, this has now been fixed in version 1.3.1.
